// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // migrate/studio/seedはpooled connection（PgBouncerのtransaction pooling）だと
    // アドバイザリーロック取得がタイムアウトすることがあるため、CLIコマンドだけは
    // 非pooled（direct）接続を使う。DIRECT_DATABASE_URL未設定の環境（ローカル開発等、
    // pooler自体が無い）ではDATABASE_URLにフォールバックする。
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
